name: CI/CD Microservices Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-publish-common:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GH_USERNAME }}
      TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Publish common module to GitHub Packages
        run: |
          cd common
          ./gradlew publish
        working-directory: ./common

  build-services:
    runs-on: ubuntu-latest
    needs: build-and-publish-common
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build all services without tests
        run: |
          chmod +x ./api-gateway/gradlew
          ./api-gateway/gradlew -p api-gateway build -x test

          chmod +x ./identity-service/gradlew
          ./identity-service/gradlew -p identity-service build -x test

          chmod +x ./candidate-service/gradlew
          ./candidate-service/gradlew -p candidate-service build -x test

          chmod +x ./employer-service/gradlew
          ./employer-service/gradlew -p employer-service build -x test

          chmod +x ./job-service/gradlew
          ./job-service/gradlew -p job-service build -x test

  docker-push:
    runs-on: ubuntu-latest
    needs: build-services
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Images
        run: |
          docker build -t phucbtdev/api-gateway ./api-gateway
          docker build -t phucbtdev/identity-service ./identity-service
          docker build -t phucbtdev/candidate-service ./candidate-service
          docker build -t phucbtdev/employer-service ./employer-service
          docker build -t phucbtdev/job-service ./job-service

          docker push phucbtdev/api-gateway
          docker push phucbtdev/identity-service
          docker push phucbtdev/candidate-service
          docker push phucbtdev/employer-service
          docker push phucbtdev/job-service

  deploy:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - name: SSH & Deploy via Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull phucbtdev/api-gateway
            docker pull phucbtdev/identity-service
            docker pull phucbtdev/candidate-service
            docker pull phucbtdev/employer-service
            docker pull phucbtdev/job-service

            docker-compose down
            docker-compose up -d
