name: CI/CD Microservices Deploy

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build and publish common module
        run: |
          cd common
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal

      - name: Build each microservice
        run: |
          cd api-gateway
          chmod +x ./gradlew
          ./gradlew build -x test
          cd ../identity-service
          chmod +x ./gradlew
          ./gradlew build -x test
          cd ../candidate-service
          chmod +x ./gradlew
          ./gradlew build -x test
          cd ../employer-service
          chmod +x ./gradlew
          ./gradlew build -x test
          cd ../job-service
          chmod +x ./gradlew
          ./gradlew build -x test

  docker-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Images
        run: |
          docker build -t phucbtdev/api-gateway ./api-gateway
          docker build -t phucbtdev/identity-service ./identity-service
          docker build -t phucbtdev/candidate-service ./candidate-service
          docker build -t phucbtdev/employer-service ./employer-service
          docker build -t phucbtdev/job-service ./job-service

          docker push phucbtdev/api-gateway
          docker push phucbtdev/identity-service
          docker push phucbtdev/candidate-service
          docker push phucbtdev/employer-service
          docker push phucbtdev/job-service

  deploy:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - name: SSH & Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull phucbtdev/api-gateway
            docker pull phucbtdev/identity-service
            docker pull phucbtdev/candidate-service
            docker pull phucbtdev/employer-service
            docker pull phucbtdev/job-service

            docker-compose down
            docker-compose up -d
