name: CI/CD Microservices Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-publish-common:
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits.*.modified, ','), 'common/')
    env:
      USERNAME: ${{ secrets.GH_USERNAME }}
      TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: common-gradle-${{ runner.os }}-${{ hashFiles('common/**') }}
          restore-keys: |
            common-gradle-${{ runner.os }}-

      - name: Publish common module to GitHub Packages
        run: |
          cd common
          chmod +x gradlew
          ./gradlew publish

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-publish-common
    if: always() # Chạy dù job trước có skip
    strategy:
      matrix:
        service: [api-gateway, identity-service, candidate-service, employer-service, job-service]
        include:
          - service: api-gateway
            port: 8080
          - service: identity-service
            port: 8081
          - service: candidate-service
            port: 8082
          - service: employer-service
            port: 8083
          - service: job-service
            port: 8084
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: phucbtdev/${{ matrix.service }}:latest
          build-args: |
            USERNAME=${{ secrets.GH_USERNAME }}
            TOKEN=${{ secrets.GH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: SSH & Deploy via Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull phucbtdev/api-gateway:latest
            docker pull phucbtdev/identity-service:latest
            docker pull phucbtdev/candidate-service:latest
            docker pull phucbtdev/employer-service:latest
            docker pull phucbtdev/job-service:latest

            docker-compose down
            docker-compose up -d